### ISSUE TITLE
depreciation warning regarding ABC

### ISSUE THREAD

**Issue by BlackZork** [podio/valideer#27]
```
.venv/lib/python3.9/site-packages/valideer/validators.py:469: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    accept_types = collections.Sequence

.venv/lib/python3.9/site-packages/valideer/validators.py:564: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    accept_types = collections.Mapping
```

If would be nice to update those imports - I see this warning in every unit test when running pytest

**Comment by yellowtailfan** [comment]
On Python 3.10, this breaks import of valideer:
```
Traceback (most recent call last):
  File "...", line 13, in <module>
    import valideer as V
  File "/home/.../.local/lib/python3.10/site-packages/valideer/__init__.py", line 2, in <module>
    from .validators import  *
  File "/home/.../.local/lib/python3.10/site-packages/valideer/validators.py", line 466, in <module>
    class HomogeneousSequence(Type):
  File "/home/.../.local/lib/python3.10/site-packages/valideer/validators.py", line 469, in HomogeneousSequence
    accept_types = collections.Sequence
AttributeError: module 'collections' has no attribute 'Sequence'
$ python3 -V
Python 3.10.4
$ pip3 show valideer
Name: valideer
Version: 0.4.2
```

**Comment by bmrobin** [comment]
would love a repo maintainer to address the open PR's in the repo that allow this support.  if not, i'm going to fork it and move along on my own
